from typing import Protocol
from uuid import UUID

from user_service.domain.models import User


class UserCache(Protocol):
    async def get_user(self, user_id: UUID) -> User | None: ...

    async def set_user(self, user: User) -> None: ...

    async def delete_user(self, user_id: UUID) -> None: ...

    async def get_permissions(self, user_id: UUID) -> list[str] | None: ...

    async def set_permissions(self, user_id: UUID, perms: list[str], *, ttl: int = 300) -> None: ...

    async def delete_permissions(self, user_id: UUID) -> None: ...
