from typing import Protocol
from uuid import UUID
from .models import UserAuth, IdentityType

class AuthRepository(Protocol):
    async def add(self, auth: UserAuth) -> None: ...

    async def get_by_identifier(self, identity_type: IdentityType, identifier: str) -> UserAuth | None: ...

    async def get_by_user_id(self, user_id: UUID, identity_type: IdentityType) -> UserAuth | None: ...

    async def save(self, auth: UserAuth) -> None: ...
