from typing import Protocol
from uuid import UUID

from user_service.domain.models import Department, Menu, Role, User, Tenant


class UserRepository(Protocol):
    async def add(self, user: User) -> None: ...

    async def save(self, user: User) -> None: ...

    async def get_by_id(self, user_id: UUID) -> User | None: ...

    async def get_by_email(self, email: str) -> User | None: ...

    async def get_by_username(self, username: str) -> User | None: ...

    async def get_by_phone(self, phone: str) -> User | None: ...

    async def get_all(self, tenant_id: UUID | None = None) -> list[User]: ...

    async def delete(self, user_id: UUID) -> None: ...


class RoleRepository(Protocol):
    async def add(self, role: Role) -> None: ...
    async def save(self, role: Role) -> None: ...
    async def get_by_id(self, role_id: UUID) -> Role | None: ...
    async def get_by_user_id(self, user_id: UUID) -> list[Role]: ...
    async def get_by_tenant_id(self, tenant_id: UUID) -> list[Role]: ...
    async def assign_role_to_user(self, user_id: UUID, role_id: UUID) -> None: ...
    async def remove_role_from_user(self, user_id: UUID, role_id: UUID) -> None: ...
    async def delete(self, role_id: UUID) -> None: ...


class MenuRepository(Protocol):
    async def add(self, menu: Menu) -> None: ...
    async def save(self, menu: Menu) -> None: ...
    async def get_by_id(self, menu_id: UUID) -> Menu | None: ...
    async def get_by_role_id(self, role_id: UUID) -> list[Menu]: ...
    async def get_by_user_id(self, user_id: UUID) -> list[Menu]: ...
    async def get_all(self) -> list[Menu]: ...
    async def assign_menu_to_role(self, role_id: UUID, menu_id: UUID) -> None: ...
    async def remove_menu_from_role(self, role_id: UUID, menu_id: UUID) -> None: ...


class DepartmentRepository(Protocol):
    async def add(self, dept: Department) -> None: ...
    async def save(self, dept: Department) -> None: ...
    async def get_by_id(self, dept_id: UUID) -> Department | None: ...
    async def get_by_tenant_id(self, tenant_id: UUID) -> list[Department]: ...
    async def get_children(self, parent_id: UUID) -> list[Department]: ...
    async def get_descendants(self, dept_id: UUID) -> list[Department]:
        """Return all departments whose ancestors string contains dept_id."""
        ...
    async def delete(self, dept_id: UUID) -> None: ...


class TenantRepository(Protocol):
    async def add(self, tenant: Tenant) -> None: ...
    async def save(self, tenant: Tenant) -> None: ...
    async def get_by_id(self, tenant_id: UUID) -> Tenant | None: ...
    async def get_by_key(self, tenant_key: str) -> Tenant | None: ...
    async def get_all(self) -> list[Tenant]: ...
    async def delete(self, tenant_id: UUID) -> None: ...
