from typing import Protocol
from uuid import UUID

from user_service.domain.models import User, Role, Menu


class UserRepository(Protocol):
    async def add(self, user: User) -> None: ...

    async def save(self, user: User) -> None: ...

    async def get_by_id(self, user_id: UUID) -> User | None: ...

    async def get_by_email(self, email: str) -> User | None: ...

    async def get_by_username(self, username: str) -> User | None: ...

    async def get_by_phone(self, phone: str) -> User | None: ...


class RoleRepository(Protocol):
    async def add(self, role: Role) -> None: ...
    async def save(self, role: Role) -> None: ...
    async def get_by_id(self, role_id: UUID) -> Role | None: ...
    async def get_by_user_id(self, user_id: UUID) -> list[Role]: ...
    async def get_by_tenant_id(self, tenant_id: UUID) -> list[Role]: ...
    async def assign_role_to_user(self, user_id: UUID, role_id: UUID) -> None: ...


class MenuRepository(Protocol):
    async def add(self, menu: Menu) -> None: ...
    async def save(self, menu: Menu) -> None: ...
    async def get_by_id(self, menu_id: UUID) -> Menu | None: ...
    async def get_by_role_id(self, role_id: UUID) -> list[Menu]: ...
    async def get_by_user_id(self, user_id: UUID) -> list[Menu]: ...
    async def assign_menu_to_role(self, role_id: UUID, menu_id: UUID) -> None: ...
