"""add_tenants_table

Revision ID: f61f8d076ecc
Revises: 0001_create_users_table
Create Date: 2026-05-05 08:32:57.973502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f61f8d076ecc'
down_revision: Union[str, Sequence[str], None] = '0001_create_users_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='操作用户ID'),
    sa.Column('action', sa.String(length=100), nullable=False, comment='操作动作'),
    sa.Column('resource', sa.String(length=100), nullable=False, comment='操作资源'),
    sa.Column('resource_id', sa.String(length=100), nullable=True, comment='资源ID'),
    sa.Column('details', sa.Text(), nullable=True, comment='操作详情(JSON)'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='操作IP'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='操作状态'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False, comment='租户ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('tenants',
    sa.Column('name', sa.String(length=100), nullable=False, comment='租户名称'),
    sa.Column('tenant_key', sa.String(length=50), nullable=False, comment='租户唯一标识符'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('contact_person', sa.String(length=64), nullable=True, comment='联系人'),
    sa.Column('contact_phone', sa.String(length=32), nullable=True, comment='联系电话'),
    sa.Column('config', sa.JSON(), nullable=False, comment='租户配置JSON'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_status'), 'tenants', ['status'], unique=False)
    op.create_index(op.f('ix_tenants_tenant_key'), 'tenants', ['tenant_key'], unique=True)
    op.alter_column('departments', 'parent_id',
               existing_type=sa.UUID(),
               comment='父部门ID',
               existing_nullable=True)
    op.alter_column('departments', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='部门名称',
               existing_nullable=False)
    op.alter_column('departments', 'ancestors',
               existing_type=sa.TEXT(),
               comment='祖级列表: 存储所有父级ID, 逗号分隔',
               existing_nullable=True)
    op.alter_column('departments', 'order_num',
               existing_type=sa.INTEGER(),
               comment='显示顺序',
               existing_nullable=False)
    op.alter_column('departments', 'tenant_id',
               existing_type=sa.UUID(),
               comment='租户ID',
               existing_nullable=False)
    op.alter_column('menus', 'parent_id',
               existing_type=sa.UUID(),
               comment='父菜单ID',
               existing_nullable=True)
    op.alter_column('menus', 'menu_name',
               existing_type=sa.VARCHAR(length=50),
               comment='菜单名称',
               existing_nullable=False)
    op.alter_column('menus', 'menu_type',
               existing_type=sa.VARCHAR(length=1),
               comment='菜单类型: M-目录, C-菜单, F-按钮(权限点)',
               existing_nullable=False)
    op.alter_column('menus', 'path',
               existing_type=sa.VARCHAR(length=255),
               comment='路由地址/API路径',
               existing_nullable=True)
    op.alter_column('menus', 'perms',
               existing_type=sa.VARCHAR(length=100),
               comment='权限标识: user:list',
               existing_nullable=True)
    op.alter_column('menus', 'icon',
               existing_type=sa.VARCHAR(length=100),
               comment='菜单图标',
               existing_nullable=True)
    op.alter_column('menus', 'order_num',
               existing_type=sa.INTEGER(),
               comment='显示顺序',
               existing_nullable=False)
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment='角色名称',
               existing_nullable=False)
    op.alter_column('roles', 'role_key',
               existing_type=sa.VARCHAR(length=50),
               comment='角色权限标识',
               existing_nullable=False)
    op.alter_column('roles', 'data_scope',
               existing_type=sa.INTEGER(),
               comment='数据范围: 1-全部数据, 2-本部门数据, 3-本人数据, 4-自定义部门',
               existing_nullable=False)
    op.alter_column('roles', 'tenant_id',
               existing_type=sa.UUID(),
               comment='租户ID',
               existing_nullable=False)
    op.alter_column('users', 'tenant_id',
               existing_type=sa.UUID(),
               comment='租户ID',
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=64),
               comment='用户名',
               existing_nullable=True)
    op.alter_column('users', 'nickname',
               existing_type=sa.VARCHAR(length=64),
               comment='用户昵称',
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=32),
               comment='手机号',
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='电子邮箱',
               existing_nullable=False)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.TEXT(),
               comment='头像链接',
               existing_nullable=True)
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='账号状态: active-正常, disabled-禁用, pending-待审核',
               existing_nullable=False)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               comment='是否为租户管理员: 0-否, 1-是',
               existing_nullable=False)
    op.alter_column('users', 'dept_id',
               existing_type=sa.UUID(),
               comment='所属部门ID',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'dept_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='所属部门ID',
               existing_nullable=True)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否为租户管理员: 0-否, 1-是',
               existing_nullable=False)
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='账号状态: active-正常, disabled-禁用, pending-待审核',
               existing_nullable=False)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='头像链接',
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='电子邮箱',
               existing_nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='手机号',
               existing_nullable=True)
    op.alter_column('users', 'nickname',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='用户昵称',
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='用户名',
               existing_nullable=True)
    op.alter_column('users', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='租户ID',
               existing_nullable=True)
    op.alter_column('roles', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='租户ID',
               existing_nullable=False)
    op.alter_column('roles', 'data_scope',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='数据范围: 1-全部数据, 2-本部门数据, 3-本人数据, 4-自定义部门',
               existing_nullable=False)
    op.alter_column('roles', 'role_key',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='角色权限标识',
               existing_nullable=False)
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='角色名称',
               existing_nullable=False)
    op.alter_column('menus', 'order_num',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='显示顺序',
               existing_nullable=False)
    op.alter_column('menus', 'icon',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='菜单图标',
               existing_nullable=True)
    op.alter_column('menus', 'perms',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='权限标识: user:list',
               existing_nullable=True)
    op.alter_column('menus', 'path',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='路由地址/API路径',
               existing_nullable=True)
    op.alter_column('menus', 'menu_type',
               existing_type=sa.VARCHAR(length=1),
               comment=None,
               existing_comment='菜单类型: M-目录, C-菜单, F-按钮(权限点)',
               existing_nullable=False)
    op.alter_column('menus', 'menu_name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='菜单名称',
               existing_nullable=False)
    op.alter_column('menus', 'parent_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='父菜单ID',
               existing_nullable=True)
    op.alter_column('departments', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='租户ID',
               existing_nullable=False)
    op.alter_column('departments', 'order_num',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='显示顺序',
               existing_nullable=False)
    op.alter_column('departments', 'ancestors',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='祖级列表: 存储所有父级ID, 逗号分隔',
               existing_nullable=True)
    op.alter_column('departments', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='部门名称',
               existing_nullable=False)
    op.alter_column('departments', 'parent_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='父部门ID',
               existing_nullable=True)
    op.drop_index(op.f('ix_tenants_tenant_key'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_status'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
